### ISSUE TITLE
DB設計をする

### ISSUE THREAD

**Issue by choco0809** [choco0809/stup#4]

**Comment by choco0809** [comment]
# DB設計

![Image](https://user-images.githubusercontent.com/99729409/198754486-76c7223c-bb92-46f3-9297-83d1b3bc43bf.png)

**Comment by cafedomancer** [comment]
- 英語の情報だけだど各テーブルや各カラムに何の情報が格納されるのか分からないので、論理設計と物理設計に分けてそれぞれの ER 図を提出してください
- 物理設計を行う場合はデータ型や制約も記載してください
- テーブル名やカラム名が Rails の規約に沿っていないので見直してください
- パスワードに関する情報を保存するカラムが見当たらないようです
- 学習のメモを記録するカラムが見当たらないようです

**Comment by choco0809** [comment]
> 英語の情報だけだど各テーブルや各カラムに何の情報が格納されるのか分からないので、論理設計と物理設計に分けてそれぞれの ER 図を提出するか、物理設計の ER 図に日本語の説明を追記してください
物理設計を行う場合はデータ型や制約も記載してください

各カラムに型、制約を記載しました。
また、補足に各項目にたいしての説明も追記しました。

> テーブル名やカラム名が Rails の規約に沿っていないので見直してください

修正しました🙏

> パスワードに関する情報を保存するカラムが見当たらないようです

 OAuth認証でしかログイン機能を実装しないため、パスワードに関する情報は保持しない想定です。

> 学習のメモを記録するカラムが見当たらないようです

失念しておりました🙇　追加いたしましたのでご確認お願いします🙏

**Comment by choco0809** [comment]
> users.name と users.email は表示されている箇所がペーパープロトタイプに見当たらないのですがどこに表示する予定ですか？

技術検証の段階で、試行錯誤する上で作成していた項目でした...
今回は不要なので修正いたしました🙏

> study_time_records.study_start_at と study_time_records.study_end_at に study_ という prefix をつけている理由を教えてください。study_time_records テーブル自体が学習記録を表しているような気がしたので prefix をあえて付けている理由が分からなかったためです

prefixをつけたほうがわかりやすいかな？と思っていましたが、たしかにテーブル名をみればどういった項目なのか推測できるため不必要ですね。

> study_time_records.study_start_at と study_time_records.study_end_at には過去の日時が常に入るならカラム名もそれが分かるように過去分詞になっていたほうがよいと思います

> study_time_records.study_start_at と study_time_records.study_end_at に NOT NULL 制約が付いていない理由を教えてください

現段階のロジックを下記のように考えているため、初期値がNULLのほうがよかったためです。
1. 学習開始時間を登録する時
`study_time_records`のlastを取得し、`end_at`がNULLの場合Discord側に前回の学習記録が終了していない（終了コマンドが実行されていない）旨をメッセージで返そうと考えています。
2. 学習終了時間を登録する時
`study_time_records`のlastを取得し、`end_at`がNULLの場合学習終了時間を更新し、`end_at`がNULL以外の場合はDiscord側に学習記録が開始されていない（開始コマンドが実行されていない）旨をメッセージで返そうと考えています。

**Comment by cafedomancer** [comment]
> 現段階のロジックを下記のように考えており、初期値がNULLのほうがよかったためです。
> 
> 1. 学習開始時間を登録する時
>    `study_time_records`のlastを取得し、`end_at`がNULLの場合Discord側に前回の学習記録が終了していない（終了コマンドが実行されていない）旨をメッセージで返そうと考えています。
> 2. 学習終了時間を登録する時
>    `study_time_records`のlastを取得し、`end_at`がNULLの場合学習終了時間を更新し、`end_at`がNULL以外の場合はDiscord側に学習記録が開始されていない（開始コマンドが実行されていない）旨をメッセージで返そうと考えています。

終了時間については分かりました。開始時間については `study_time_records` のレコードが作成される場合には必ず設定されませんか？ そうであるなら `started_at` には NOT NULL 制約が必要なんじゃないでしょうか。

* * *
テーブル名の日本語での説明がまだ加えられていないので加えてください。テーブル名が妥当であるかを検証する目的とシステム内で使われる用語を整理して一貫したものを使う目的があります。

**Comment by choco0809** [comment]
@cafedomancer 

> 終了時間については分かりました。開始時間については study_time_records のレコードが作成される場合には必ず設定されませんか？ そうであるなら started_at には NOT NULL 制約が必要なんじゃないでしょうか。

たしかに、`started_at`には必ず何らかしらの値が入りますね。

> テーブル名の日本語での説明がまだ加えられていないので加えてください。テーブル名が妥当であるかを検証する目的とシステム内で使われる用語を整理して一貫したものを使う目的があります。

念のため、`users`の説明も記載しました🙏

**Comment by cafedomancer** [comment]
確認しました。OK です 🙆
